site_name: mozio_app
site_description: A test project
repo_url: https://github.com/drys262/mozio-app-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/drys262">drys262</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
