# Generated by Django 2.1.9 on 2019-06-19 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None), default=[0, 0], size=None),
            preserve_default=False,
        ),
    ]
