# Generated by Django 2.1.9 on 2019-06-19 07:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20190619_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, null=True, size=None),
        ),
    ]
